# Generated by Django 5.2.1 on 2025-05-13 19:16

from django.db import migrations, models
from portal.migrations import load_json_fixture, parse_date_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def create_sample_books(apps, schema_editor):
        Book = apps.get_model('portal', 'Book')
        books_data = load_json_fixture('books.json')
        books_data = parse_date_fields(books_data, ['publication_date'])

        Book.objects.bulk_create([Book(**book) for book in books_data])

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.RunPython(create_sample_books),
    ]
