# Generated by Django 5.2.1 on 2025-05-13 19:25

from django.db import migrations, models
from portal.migrations import load_json_fixture


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    def create_static_texts(apps, schema_editor):
        StaticText = apps.get_model('portal', 'StaticText')
        texts_data = load_json_fixture('static_texts.json')

        StaticText.objects.bulk_create([StaticText(**item) for item in texts_data])

    operations = [
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RunPython(create_static_texts),
    ]
